SQL_InjectionResearchProject/Models/DataAccess.cs
using Microsoft.AspNetCore.Mvc;
using MySqlConnector;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace SQL_InjectionResearchProject.Models
{
    [Route("[controller]/[action]")]
    [ApiController]
    public class DataAccess : Controller 
    {
        private readonly string connectionstring = "Server=studmysql01.fhict.local;Uid=dbi457726;Database=dbi457726;Pwd=Banaan12;";

        [HttpPost]
        public void AddData(string productname, string description, string brand, int price)
        {
            using MySqlConnection con = new(connectionstring);
            con.Open();

            MySqlCommand cmd = new($"INSERT INTO `product` (`ProductName`, `Description`, `Brand`, `Price`) VALUES (?productname, ?description, ?brand, ?price) ", con);
            cmd.Parameters.AddWithValue("?productname", productname);
            cmd.Parameters.AddWithValue("?description", description);
            cmd.Parameters.AddWithValue("?brand", brand);
            cmd.Parameters.AddWithValue("?price", price);

            MySqlDataReader reader = cmd.ExecuteReader();
            con.Close();
        }

        public void UpdateData(string productname, string description, string brand, int price, int id)
        {
            using MySqlConnection con = new(connectionstring);
            con.Open();

            MySqlCommand cmd = new($"UPDATE `product` SET `ProductName`=?productname,`Description`=?description,`Brand`=?brand,`Price`=?price WHERE `Id`=?Id", con);
            cmd.Parameters.AddWithValue("?productname", productname);
            cmd.Parameters.AddWithValue("?description", description);
            cmd.Parameters.AddWithValue("?brand", brand);
            cmd.Parameters.AddWithValue("?price", price);
            cmd.Parameters.AddWithValue("?Id", id);

            MySqlDataReader reader = cmd.ExecuteReader();
        }

        public void DeleteData(int id)
        {
            using MySqlConnection con = new(connectionstring);
            con.Open();

            MySqlCommand cmd = new($"DELETE FROM `product` WHERE `Id` =?id", con);
            cmd.Parameters.AddWithValue("?id", id);

            MySqlDataReader reader = cmd.ExecuteReader();
        }
        [HttpGet]
        public string GetProductData(int id)
        {
            DataModel data = new();

            using MySqlConnection con = new(connectionstring);
            con.Open();

            MySqlCommand cmd = new($"SELECT * FROM `product` WHERE Id=@id", con);
            cmd.Parameters.AddWithValue("@id", id);
            MySqlDataReader reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                data.ProductName = reader["ProductName"].ToString();
                data.Description = reader["Description"].ToString();
                data.Brand = reader["Brand"].ToString();
                data.Price = int.Parse(reader["Price"].ToString());
                data.Id = int.Parse(reader["Id"].ToString());
            }
            reader.Close();
            Console.WriteLine(data);
            var json = JsonConvert.SerializeObject(data);
            return (json);
        }
        [HttpGet]
        public string GetData()
        {
            List<DataModel> data = new();

            using MySqlConnection con = new(connectionstring);
            con.Open();

            MySqlCommand cmd = new($"SELECT * FROM `product`", con);
            MySqlDataReader reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                DataModel datas = new();
                datas.ProductName = reader["ProductName"].ToString();
                datas.Description = reader["Description"].ToString();
                datas.Brand = reader["Brand"].ToString();
                datas.Price = int.Parse(reader["Price"].ToString());
                datas.Id = int.Parse(reader["Id"].ToString());
                data.Add(datas);
            }
            reader.Close();
            Console.WriteLine(data);
            var json = JsonConvert.SerializeObject(data);
            return (json);
        }

    }
}

SQL_InjectionResearchProject/Models/DataModel.cs
namespace SQL_InjectionResearchProject.Models
{
    public class DataModel
    {
        public string? ProductName { get; set; }
        public string? Description { get; set; }
        public string? Brand { get; set; }
        public int? Price { get; set; }
        public int Id { get; set; }
    }
}

SQL_InjectionResearchProject/Models/ErrorViewModel.cs
using System;

namespace SQL_InjectionResearchProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SQL_InjectionResearchProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SQL_InjectionResearchProject.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SQL_InjectionResearchProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SQL_InjectionResearchProject/Controllers/SQLController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SQL_InjectionResearchProject.Models;
using System.Collections.Generic;

namespace SQL_InjectionResearchProject.Controllers
{
    public class SQLController : Controller
    {
        DataAccess dataAcces = new();
        public ActionResult Index()
        {
            var list = JsonConvert.DeserializeObject<List<DataModel>>(dataAcces.GetData());
            return View(list);
        }

        public ActionResult Details(int id)
        {
            var datamodel = JsonConvert.DeserializeObject<DataModel>(dataAcces.GetProductData(id));
            return View(datamodel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string productname, string description, string brand, int price)
        {
            try
            {
                dataAcces.AddData(productname, description, brand, price);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var datamodel = JsonConvert.DeserializeObject<DataModel>(dataAcces.GetProductData(id));
            return View(datamodel);
        }

        [HttpPost]
        public ActionResult Edit(int id, string productname, string description, string brand, int price)
        {
                dataAcces.UpdateData(productname, description,brand,price,id);
                return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete(int id)
        {
            var datamodel = JsonConvert.DeserializeObject<DataModel>(dataAcces.GetProductData(id));
            return View(datamodel);
        }
        [HttpPost]
        public ActionResult DeleteConfirm(int id)
        {
            try
            {
                dataAcces.DeleteData(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Delete));
            }
        }
    }
}

SQL_InjectionResearchProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SQL_InjectionResearchProject/Views/SQL/Create.cshtml
@model SQL_InjectionResearchProject.Models.DataModel

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>View</h1>

<h4>DataModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SQL_InjectionResearchProject/Views/SQL/Delete.cshtml
@model SQL_InjectionResearchProject.Models.DataModel

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>View</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DataModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirm">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SQL_InjectionResearchProject/Views/SQL/Details.cshtml
@model SQL_InjectionResearchProject.Models.DataModel

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>View</h1>

<div>
    <h4>DataModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { @id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

SQL_InjectionResearchProject/Views/SQL/Edit.cshtml
@model SQL_InjectionResearchProject.Models.DataModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>DataModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SQL_InjectionResearchProject/Views/SQL/Index.cshtml
@model IEnumerable<SQL_InjectionResearchProject.Models.DataModel>

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>View</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { @id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { @id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { @id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

SQL_InjectionResearchProject/Views/SQL/ww.cshtml
@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <div>
    <h2>PostApiTest</h2>
    <b>Productnaam</b><br />
    <input type="text" id="txtName" /><br />
    <b>Product beschrijving</b><br />
    <input type="text" id="txtDescription" /><br />
    <b>Product merk</b><br />
    <input type="text" id="txtBrand" /><br />
    <b>Product prijs</b><br />
    <input type="text" id="txtPrice" /><br />
    <input type="button" value="Save" id="verstuur" />
</div>
@section Scripts{
<script src="~/lib/jquery/jquery.js"></script>
<script type="text/javascript">
        function AddProduct(){
        jQuery.support.cors = true;
        var product = {
            ProductName: $('#txtName').val(),
            Description: $('#txtDescription').val(),
            Brand: $('#txtBrand').val(),
            Price: $('#txtPrice').val()
        };

        $ajax.({
            url: 'https://localhost:44397/DataAcces/AddData',
            type: 'POST',
            data: JSON.stringify(product),
            contentType: "application/json;charset=utf-8",
            succes: function (data){

            },
            error: function(x,y,z){

            }
        });
        console.log(product);
    }
    $("#verstuur").click(AddProduct());
</script>
}
</body>

SQL_InjectionResearchProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SQL_InjectionResearchProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SQL_InjectionResearchProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SQL" asp-action="Index">Proudct data</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SQL_InjectionResearchProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>